-- Problem 2
--
-- Each new term in the Fibonacci sequence is generated by adding
-- the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed
-- four million, find the sum of the even-valued terms.

module Problem_2 where

problem_2 :: Integer
problem_2 = evenFibonacciSum 4000000

evenFibonacciSum :: Integer -> Integer
evenFibonacciSum limit = sum $ filter even $ takeWhile (< limit) fibonacciSequence
  where fibonacciSequence = 1 : 2 : zipWith (+) fibonacciSequence (tail fibonacciSequence)
